/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const TeleviziaLazyRouteImport = createFileRoute('/televizia')()
const ONasLazyRouteImport = createFileRoute('/o-nas')()
const KontaktLazyRouteImport = createFileRoute('/kontakt')()
const InternetLazyRouteImport = createFileRoute('/internet')()

const TeleviziaLazyRoute = TeleviziaLazyRouteImport.update({
  id: '/televizia',
  path: '/televizia',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/televizia.lazy').then((d) => d.Route))
const ONasLazyRoute = ONasLazyRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/o-nas.lazy').then((d) => d.Route))
const KontaktLazyRoute = KontaktLazyRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/kontakt.lazy').then((d) => d.Route))
const InternetLazyRoute = InternetLazyRouteImport.update({
  id: '/internet',
  path: '/internet',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/internet.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/internet': typeof InternetLazyRoute
  '/kontakt': typeof KontaktLazyRoute
  '/o-nas': typeof ONasLazyRoute
  '/televizia': typeof TeleviziaLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/internet': typeof InternetLazyRoute
  '/kontakt': typeof KontaktLazyRoute
  '/o-nas': typeof ONasLazyRoute
  '/televizia': typeof TeleviziaLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/internet': typeof InternetLazyRoute
  '/kontakt': typeof KontaktLazyRoute
  '/o-nas': typeof ONasLazyRoute
  '/televizia': typeof TeleviziaLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/internet' | '/kontakt' | '/o-nas' | '/televizia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/internet' | '/kontakt' | '/o-nas' | '/televizia'
  id: '__root__' | '/' | '/internet' | '/kontakt' | '/o-nas' | '/televizia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InternetLazyRoute: typeof InternetLazyRoute
  KontaktLazyRoute: typeof KontaktLazyRoute
  ONasLazyRoute: typeof ONasLazyRoute
  TeleviziaLazyRoute: typeof TeleviziaLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/televizia': {
      id: '/televizia'
      path: '/televizia'
      fullPath: '/televizia'
      preLoaderRoute: typeof TeleviziaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internet': {
      id: '/internet'
      path: '/internet'
      fullPath: '/internet'
      preLoaderRoute: typeof InternetLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InternetLazyRoute: InternetLazyRoute,
  KontaktLazyRoute: KontaktLazyRoute,
  ONasLazyRoute: ONasLazyRoute,
  TeleviziaLazyRoute: TeleviziaLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
